#!/usr/bin/env bash
ENVIRONMENT_NAME_VALUE="Prod"
WEB_API_HOST_VALUE=""
WEB_API_KEY_VALUE=""
APPLICATION_NAME_VALUE="Mobile Template"
PACKAGE_NAME_VALUE="com.companyname.mobiletemplate"
APP_CENTER_DROID_VALUE="12480d3f-eb5d-452c-a7ef-d06ce2b50e30"
APP_CENTER_IOS_VALUE=""
VERSION_NUMBER_PREFIX="1.0."