#!/usr/bin/env bash
ENVIRONMENT_NAME_VALUE="Dev"
WEB_API_HOST_VALUE=""
WEB_API_KEY_VALUE=""
APPLICATION_NAME_VALUE="Dev - Mobile Template"
PACKAGE_NAME_VALUE="com.companyname.mobiletemplate.dev"
APP_CENTER_DROID_VALUE=""
APP_CENTER_IOS_VALUE=""
VERSION_NUMBER_PREFIX="0.0."